# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSticker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("sticker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owners", to="stickers.sticker")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stickers", to="stickers.user")),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("user", "sticker")},
            },
        ),
    ]
